name: Test PHP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      enable_upterm:
        description: 'Set "true" to enable upterm session.'
        required: true

jobs:
  test-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit tests

      - name: Setup upterm session
        if: ${{ !cancelled() && github.event.inputs.enable_upterm == 'true' }}
        uses: lhotari/action-upterm@v1
        with:
          wait-timeout-minutes: 5
